/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d35f8d6d011cc097f0543fe
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { PedidosService } from '../../services/pedidos.service';
// Import Models
import { Pedidos } from '../../domain/pizza_db/pedidos';

// START - USED SERVICES
/**
* pedidosService.create
*	@description CRUD ACTION create
*
* pedidosService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* pedidosService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Pedidos
 */
@Component({
    selector: 'app-pedidos-edit',
    templateUrl: 'pedidos-edit.component.html',
    styleUrls: ['pedidos-edit.component.css']
})
export class PedidosEditComponent implements OnInit {
    item: Pedidos;
    model: Pedidos;
    formValid: Boolean;

    constructor(
    private pedidosService: PedidosService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Pedidos();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.pedidosService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save Pedidos
     *
     * @param {boolean} formValid Form validity check
     * @param Pedidos item Pedidos to save
     */
    save(formValid: boolean, item: Pedidos): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.pedidosService.update(item).subscribe(data => this.goBack());
            } else {
                this.pedidosService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



