/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d35f8d6d011cc097f0543fe
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ClienteService } from '../../services/cliente.service';
// Import Models
import { Cliente } from '../../domain/pizza_db/cliente';

// START - USED SERVICES
/**
* clienteService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* clienteService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Cliente
 * @class ClienteListComponent
 */
@Component({
    selector: 'app-cliente-list',
    templateUrl: './cliente-list.component.html',
    styleUrls: ['./cliente-list.component.css']
})
export class ClienteListComponent implements OnInit {
    list: Cliente[];
    search: any = {};
    idSelected: string;
    constructor(
        private clienteService: ClienteService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.clienteService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Cliente to remove
     *
     * @param {string} id Id of the Cliente to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Cliente
     */
    deleteItem() {
        this.clienteService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
