<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d35f8d6d011cc097f0543fe
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbpizza_dbManager.php';
	
/*
 * SCHEMA DB pedidos
 * 
	{
		direccion: {
			type: 'String'
		},
		estado: {
			type: 'String'
		},
		fecha: {
			type: 'Date'
		},
		id_cliente: {
			type: 'Integer', 
			required : true
		},
		id_producto: {
			type: 'Integer', 
			required : true
		},
		total: {
			type: 'Integer'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/pedidos',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'direccion'	=> isset($body->direccion)?$body->direccion:'',
		'estado'	=> isset($body->estado)?$body->estado:'',
		'fecha'	=> isset($body->fecha)?$body->fecha:'',
		'id_cliente'	=> $body->id_cliente,
		'id_producto'	=> $body->id_producto,
		'total'	=> isset($body->total)?$body->total:'',
			);

	$obj = makeQuery("INSERT INTO pedidos (_id, direccion, estado, fecha, id_cliente, id_producto, total )  VALUES ( null, :direccion, :estado, :fecha, :id_cliente, :id_producto, :total   )", $params, false);

	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/pedidos/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM pedidos WHERE _id = :id LIMIT 1", $params);

});
	
//CRUD - GET ONE
	
$app->get('/pedidos/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM pedidos WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/pedidos',	function () use ($app){
	makeQuery("SELECT * FROM pedidos");
});


//CRUD - EDIT

$app->post('/pedidos/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'direccion'	    => isset($body->direccion)?$body->direccion:'',
		'estado'	    => isset($body->estado)?$body->estado:'',
		'fecha'	    => isset($body->fecha)?$body->fecha:'',
		'id_cliente'	    => $body->id_cliente,
		'id_producto'	    => $body->id_producto,
		'total'	    => isset($body->total)?$body->total:''	);

	$obj = makeQuery("UPDATE pedidos SET  direccion = :direccion,  estado = :estado,  fecha = :fecha,  id_cliente = :id_cliente,  id_producto = :id_producto,  total = :total   WHERE _id = :id LIMIT 1", $params, false);

	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>